name: "tools"
version: 1.0.0
timeout: 3000
db:
  name:
  host: 192.168.2.39
  port: 3306
  username: root
  password: 123456

cache:
  name:
  host: 192.168.2.39
  port: 3306
  username: root
  password: 123456