name: utils
version: 1.0.0
timeout: 3000
db:
  name: tools
  category: mysql
  host: 192.168.0.132
  port: 3306
  username: root
  password: 123456

cache:
  name: tools
  category: redis
  host: 192.168.0.132
  port: 3306
  username: root
  password: 123456